### ISSUE TITLE
Cleartext HTTP traffic to 10.0.2.2 not permitted

### ISSUE THREAD

**Issue by misici234** [AS-Devs/signalr_flutter#1]
Hi,

I created brand new Flutter project, copied and pasted your code there added my server URL and hub name and got the following error
Cleartext HTTP traffic to 10.0.2.2 not permitted
The Server URL points to SignalR server which works good with other packages (therefore, that one is not a problem). Please see the attached screenshot. I tried many thing to resolve this problem and I was just getting other errors. Please help.
![image](https://user-images.githubusercontent.com/49884093/91754442-64166600-eb97-11ea-8b4e-133f5ac810ae.png)

**Comment by AyonAB** [comment]
@misici234 you are trying to connect with an **HTTP** url instead of **HTTPS**. I will recommend you to move your url to **HTTPS**.

But if you absolutely need to connect with a HTTP url, then you need to add the following lines in the manifest of your android source.

```xml
<application android:usesCleartextTraffic="true">
    </application>
```

This is because of [Network Security Config](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted), which says,

> Starting with Android 9 (API level 28), cleartext support is disabled by default.

If you need more helps on this, read this Stackoverflow [Thread](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted).
